general:
  data_base_dir: /app/data
modules:
  DataSorter:
    base_dir: /app/data/sorted
    structure: '%SeriesInstanceUID/dicom/%SOPInstanceUID.dcm'
  DsegConverter:
    #dicomseg_json_path: /app/aimi/totalsegmentator/config/dicomseg_metadata_whole.json
    dicomseg_yml_path: /app/aimi/totalsegmentator/scripts/dseg.yml
    skip_empty_slices: True
  TotalSegmentatorRunner:
    use_fast_mode: true
